name: run-linting

on:
    push:
    pull_request:

jobs:
    run-linting:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Execute linting
              run: |
                vendor/bin/php-cs-fixer fix --dry-run
                vendor/bin/phpcs --colors --report-full
